========= DDOTMEMBER ===========

DROP TABLE DDOTMEMBER
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_DDOTMEMBER;

CREATE TABLE DDOTMEMBER(
	SEQ NUMBER(8) PRIMARY KEY,
	ID VARCHAR2(50) NOT NULL,
	PWD VARCHAR2(50) NOT NULL,
	EMAIL VARCHAR2(50) NOT NULL,
	POINT NUMBER(8) NOT NULL,
	NICKNAME VARCHAR2(50) UNIQUE,
	PIC VARCHAR2(50) ,
	INTRO VARCHAR2(50) NOT NULL,
	AUTH NUMBER(2)
);

CREATE SEQUENCE SEQ_DDOTMEMBER
START WITH 1 INCREMENT BY 1;

select point from DDOTMEMBER where id='zxcv'

update DDOTMEMBER set point='10000' where id='zxcv';

========= DDOTMEMBER ===========

========= DDOTBBS ===========

DROP TABLE DDOTBBS
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_DDOTBBS;

CREATE TABLE DDOTBBS(
	SEQ NUMBER(8) PRIMARY KEY,
	NICKNAME VARCHAR2(50) NOT NULL,
	CATEGORY VARCHAR2(50) NOT NULL,
	SUBCATEGORY VARCHAR2(50) NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	WDATE DATE NOT NULL,
	UP NUMBER(20),
	DOWN NUMBER(20),
	READCOUNT NUMBER(20),
	DEL NUMBER(2)
);

CREATE SEQUENCE SEQ_DDOTBBS
START WITH 1 INCREMENT BY 1;

ALTER TABLE DDOTBBS
ADD CONSTRAINT FK_DDOTBBS_NICKNAME FOREIGN KEY(NICKNAME)
REFERENCES DDOTMEMBER(NICKNAME);

========= DDOTBBS ===========

========= DDOTCOMM ===========

DROP TABLE DDOTCOMM
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_DDOTCOMM;

CREATE TABLE DDOTCOMM(
	SEQ NUMBER(8) PRIMARY KEY,
	NICKNAME VARCHAR2(50) NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	WDATE DATE NOT NULL,
	UP NUMBER(20),
	DOWN NUMBER(20),
	READCOUNT NUMBER(20),
	DEL NUMBER(2)
);

CREATE SEQUENCE SEQ_DDOTCOMM
START WITH 1 INCREMENT BY 1;

ALTER TABLE DDOTCOMM
ADD CONSTRAINT FK_DDOTCOMM_NICKNAME FOREIGN KEY(NICKNAME)
REFERENCES DDOTMEMBER(NICKNAME);

========= DDOTCOMM ===========

========= DDOTUPDOWN ===========

DROP TABLE DDOTUPDOWN
CASCADE CONSTRAINTS;

CREATE TABLE DDOTUPDOWN(
	BBS_SEQ NUMBER(8),
	COMM_SEQ NUMBER(8),
	NICKNAME VARCHAR2(50) NOT NULL,
	UPDOWN NUMBER(2) NOT NULL	--안눌렀을때 0 눌렀을때 1
);

ALTER TABLE DDOTUPDOWN
ADD CONSTRAINT FK_DDOTUPDOWN_NICKNAME FOREIGN KEY(NICKNAME)
REFERENCES DDOTMEMBER(NICKNAME);

ALTER TABLE DDOTUPDOWN
ADD CONSTRAINT FK_DDOTUPDOWN_BBS_SEQ FOREIGN KEY(BBS_SEQ)
REFERENCES DDOTBBS(SEQ);

ALTER TABLE DDOTUPDOWN
ADD CONSTRAINT FK_DDOTUPDOWN_COMM_SEQ FOREIGN KEY(COMM_SEQ)
REFERENCES DDOTCOMM(SEQ);

========= DDOTUPDOWN ===========

========= DDOTMESSAGE ===========

DROP TABLE DDOTMESSAGE
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_DDOTMESSAGE;

CREATE TABLE DDOTMESSAGE(
	SEQ NUMBER(8) PRIMARY KEY,
	NICKNAME VARCHAR2(50) NOT NULL,
	SENDTO VARCHAR2(50),
	CONTENT VARCHAR2(1000) NOT NULL,
	WDATE DATE NOT NULL,
	SENDREAD NUMBER(2),
	NICKREAD NUMBER(2),
	SENDDEL NUMBER(2),
	NICKDEL NUMBER(2)
	AUTH NUMBER(2)
);

CREATE SEQUENCE SEQ_DDOTMESSAGE
START WITH 1 INCREMENT BY 1;

ALTER TABLE DDOTMESSAGE
ADD CONSTRAINT FK_DDOTMESSAGE_NICKNAME FOREIGN KEY(NICKNAME)
REFERENCES DDOTMEMBER(NICKNAME);

========= DDOTMESSAGE ===========

========= DDOTATTENDANCE ===========
DROP TABLE DDOTATTENDANCE
CASCADE CONSTRAINTS;

CREATE TABLE DDOTATTENDANCE(
    NICKNAME VARCHAR2(50) NOT NULL,
    DAY01 NUMBER(1) NOT NULL,
    DAY02 NUMBER(1) NOT NULL,
    DAY03 NUMBER(1) NOT NULL,
    DAY04 NUMBER(1) NOT NULL,
    DAY05 NUMBER(1) NOT NULL,
    DAY06 NUMBER(1) NOT NULL,
    DAY07 NUMBER(1) NOT NULL,
    DAY08 NUMBER(1) NOT NULL,
    DAY09 NUMBER(1) NOT NULL,
    DAY10 NUMBER(1) NOT NULL,
    DAY11 NUMBER(1) NOT NULL,
    DAY12 NUMBER(1) NOT NULL,
    DAY13 NUMBER(1) NOT NULL,
    DAY14 NUMBER(1) NOT NULL,
    DAY15 NUMBER(1) NOT NULL,
    DAY16 NUMBER(1) NOT NULL,
    DAY17 NUMBER(1) NOT NULL,
    DAY18 NUMBER(1) NOT NULL,
    DAY19 NUMBER(1) NOT NULL,
    DAY20 NUMBER(1) NOT NULL,
    DAY21 NUMBER(1) NOT NULL,
    DAY22 NUMBER(1) NOT NULL,
    DAY23 NUMBER(1) NOT NULL,
    DAY24 NUMBER(1) NOT NULL,
    DAY25 NUMBER(1) NOT NULL,
    DAY26 NUMBER(1) NOT NULL,
    DAY27 NUMBER(1) NOT NULL,
    DAY28 NUMBER(1) NOT NULL,
    DAY29 NUMBER(1) NOT NULL,
    DAY30 NUMBER(1) NOT NULL,
    DAY31 NUMBER(1) NOT NULL
)

ALTER TABLE DDOTATTENDANCE
ADD CONSTRAINT FK_DDOTATTENDANCE_NICKNAME FOREIGN KEY(NICKNAME)
REFERENCES DDOTMEMBER(NICKNAME);


========= DDOTATTENDANCE ===========

========= DDOTREPLY ===========

DROP TABLE DDOTREPLY
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_DDOTREPLY;

CREATE TABLE DDOTREPLY(
	SEQ NUMBER(8) PRIMARY KEY,
	BBS_SEQ NUMBER(8),
	COMM_SEQ NUMBER(8),
	NICKNAME VARCHAR2(50) NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	WDATE DATE NOT NULL,
	DEL NUMBER(2)
);

CREATE SEQUENCE SEQ_DDOTREPLY
START WITH 1 INCREMENT BY 1;

ALTER TABLE DDOTREPLY
ADD CONSTRAINT FK_DDOTREPLY_NICKNAME FOREIGN KEY(NICKNAME)
REFERENCES DDOTMEMBER(NICKNAME);

ALTER TABLE DDOTREPLY
ADD CONSTRAINT FK_DDOTREPLY_BBS_SEQ FOREIGN KEY(BBS_SEQ)
REFERENCES DDOTBBS(SEQ);

ALTER TABLE DDOTREPLY
ADD CONSTRAINT FK_DDOTREPLY_COMM_SEQ FOREIGN KEY(COMM_SEQ)
REFERENCES DDOTCOMM(SEQ);

========= DDOTREPLY ===========
